/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package simple.contact.manager;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author adi
 */
public class MainPage extends javax.swing.JFrame {

    static final String DB_URL = "jdbc:mysql://localhost:3306/contact_manager";
    static final String DB_DRV = "com.mysql.jdbc.Driver";
    static final String DB_USER = "root";
    static final String DB_PASSWD = "";
    boolean edit = false, clicked=false;
    String editKontak;
    String idKontak;
    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        showData();
    }
    
    public void clearField(){
        fieldNama.setText("");
        fieldTelepon.setText("");
        fieldTanggalLahir.setText("");
        fieldAlamat.setText("");
        fieldAgama.setText("");
        fieldEmail.setText("");
        fieldPekerjaan.setText("");
        fieldHobi.setText("");
    }
    
    public void showData(){
        Connection connection;
        Statement statement;
        ResultSet rs;
        //PreparedStatement preparedStatement;
        
        
        DefaultTableModel model = (DefaultTableModel) tableKontak.getModel();
        model.setRowCount(0);
        try{
            connection = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWD);
            statement = (Statement) connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM kontak");
            Object [] row = new Object[9];
            while(rs.next()){
                row[0] = rs.getString("id_kontak");
                row[1] = rs.getString("nama");
                row[2] = rs.getString("no_telepon");
                row[3] = rs.getString("alamat");
                row[4] = rs.getString("tanggal_lahir");
                row[5] = rs.getString("agama");
                row[6] = rs.getString("email");
                row[7] = rs.getString("pekerjaan");
                row[8] = rs.getString("hobi");
                model.addRow(row);
            }
        }catch(Exception e){
        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        fieldPencarian = new javax.swing.JTextField();
        buttonPencarian = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableKontak = new javax.swing.JTable();
        addButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fieldNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        fieldTelepon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        fieldAlamat = new javax.swing.JTextField();
        profileImage = new javax.swing.JLabel();
        imageButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        labelPekerjaan = new javax.swing.JLabel();
        fieldPekerjaan = new javax.swing.JTextField();
        fieldHobi = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fieldAgama = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        fieldTanggalLahir = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabel Kontak"));

        fieldPencarian.setText("Cari nama anggota");

        buttonPencarian.setText("Search");
        buttonPencarian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPencarianActionPerformed(evt);
            }
        });

        tableKontak.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Kontak", "Nama"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableKontak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableKontakMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableKontak);

        addButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        addButton.setText("Add");
        addButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(buttonPencarian)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPencarian)
                    .addComponent(fieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 30, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Form Kontak"));

        jLabel1.setText("Nama");

        fieldNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNamaActionPerformed(evt);
            }
        });

        jLabel2.setText("No Telepon");

        jLabel3.setText("Alamat");

        profileImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/simple/contact/manager/jembatan.jpg"))); // NOI18N

        imageButton.setText("Tambah Gambar");
        imageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                imageButtonActionPerformed(evt);
            }
        });

        jLabel5.setText("Tanggal Lahir");

        jLabel6.setText("Email");

        fieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEmailActionPerformed(evt);
            }
        });

        labelPekerjaan.setText("Pekerjaan");

        fieldHobi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldHobiActionPerformed(evt);
            }
        });

        jLabel8.setText("Hobi");

        jLabel9.setText("Agama");

        saveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 253, Short.MAX_VALUE))
                            .addComponent(fieldHobi, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldPekerjaan)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(fieldTanggalLahir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelPekerjaan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldAgama, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fieldEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(fieldAlamat)
                            .addComponent(fieldTelepon)
                            .addComponent(fieldNama))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(imageButton)
                                .addGap(143, 143, 143))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(45, 45, 45))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldTanggalLahir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldAgama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPekerjaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fieldPekerjaan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel8)
                        .addGap(9, 9, 9)
                        .addComponent(fieldHobi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(profileImage, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imageButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPencarianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPencarianActionPerformed
        // TODO add your handling code here:
        String key = fieldPencarian.getText();
        DefaultTableModel model = (DefaultTableModel) tableKontak.getModel();
        model.setRowCount(0);
        
        Connection connection;
        Statement statement;
        ResultSet rs;
        
        if(!key.isEmpty()){
            //System.out.println("000");
            System.out.println(key);
            try{
                connection = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWD);
                statement = (Statement) connection.createStatement();
                rs = statement.executeQuery("SELECT * FROM kontak where nama like '%"+key+"%'");
                Object [] row = new Object[9];
                while(rs.next()){
                    row[0] = rs.getString("id_kontak");
                    row[1] = rs.getString("nama");
                    row[2] = rs.getString("no_telepon");
                    row[3] = rs.getString("alamat");
                    row[4] = rs.getString("tanggal_lahir");
                    row[5] = rs.getString("agama");
                    row[6] = rs.getString("email");
                    row[7] = rs.getString("pekerjaan");
                    row[8] = rs.getString("hobi");
                    model.addRow(row);
                }
            }catch(Exception e){
            }
        }
        else{
            showData();
        }
        
    }//GEN-LAST:event_buttonPencarianActionPerformed

    private void fieldNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNamaActionPerformed

    private void fieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEmailActionPerformed

    private void fieldHobiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldHobiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldHobiActionPerformed

    private void addButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButtonActionPerformed
        // TODO add your handling code here:
        edit=false;
        clearField();
        clicked=false;
        
        
    }//GEN-LAST:event_addButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // TODO add your handling code here:
        Connection connection;
        Statement statement;
        ResultSet resultSet;
        PreparedStatement preparedStatement;
        if(clicked){
            try{
                connection = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWD);
                statement = (Statement) connection.createStatement();
                preparedStatement = connection.prepareStatement("DELETE FROM kontak where id_kontak=?");
                preparedStatement.setString(1, idKontak);
                preparedStatement.executeUpdate();
            }catch(Exception e){
            
            }
            
            showData();
            clearField();
            edit=false;
        }
        
        clicked=false;
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        clicked=false;
        Connection connection;
        Statement statement;
        ResultSet resultSet;
        PreparedStatement preparedStatement;
        
        String nama = fieldNama.getText();
        String no_telepon = fieldTelepon.getText();
        String alamat = fieldAlamat.getText();
        String tanggalLahir = fieldTanggalLahir.getText();
        String agama = fieldAgama.getText();
        String email = fieldEmail.getText();
        String pekerjaan = fieldPekerjaan.getText();
        String hobi = fieldHobi.getText();
        
        //kalau edit false, insert data baru
        if(!edit){
            try{
            //Class.forName("com.mysql.jdbc.driver");
                connection = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWD);
                statement = (Statement) connection.createStatement();
                preparedStatement = connection.prepareStatement("INSERT INTO kontak values("
                    + "default,?,?,?,?,?,?,?,?)");
                preparedStatement.setString(1, nama);
                preparedStatement.setString(2, no_telepon);
                preparedStatement.setString(3, alamat);
                preparedStatement.setString(4, tanggalLahir);
                preparedStatement.setString(5, agama);
                preparedStatement.setString(6, email);
                preparedStatement.setString(7, pekerjaan);
                preparedStatement.setString(8, hobi);
                preparedStatement.executeUpdate();
            }catch(Exception e){
                System.out.println(e);
            }
        }
        else{
            try{
            //Class.forName("com.mysql.jdbc.driver");
                connection = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWD);
                statement = (Statement) connection.createStatement();
                preparedStatement = connection.prepareStatement("UPDATE kontak set "
                        + "nama=?,no_telepon=?,alamat=?,tanggal_lahir=?,"
                        + "agama=?,email=?,pekerjaan=?,hobi=? WHERE id_kontak=?");
                preparedStatement.setString(1, nama);
                preparedStatement.setString(2, no_telepon);
                preparedStatement.setString(3, alamat);
                preparedStatement.setString(4, tanggalLahir);
                preparedStatement.setString(5, agama);
                preparedStatement.setString(6, email);
                preparedStatement.setString(7, pekerjaan);
                preparedStatement.setString(8, hobi);
                preparedStatement.setString(9, idKontak);
                preparedStatement.executeUpdate();
            }catch(Exception e){
                System.out.println(e);
            }
            //edit=false;
        }
        
        
        //System.out.prit
        clearField();
        edit=false;
        
        showData();
        
    }//GEN-LAST:event_saveButtonActionPerformed

    private void imageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_imageButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_imageButtonActionPerformed

    private void tableKontakMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableKontakMouseClicked
        // TODO add your handling code here:
        //edit=true;
        DefaultTableModel model = (DefaultTableModel)tableKontak.getModel();
        int selectedRow = tableKontak.getSelectedRow();
        idKontak = model.getValueAt(selectedRow, 0).toString();
        
        Connection connection;
        Statement statement;
        ResultSet rs;
        PreparedStatement preparedStatement;
        
        try{
            connection = (Connection) DriverManager.getConnection(DB_URL,DB_USER,DB_PASSWD);
            statement = (Statement) connection.createStatement();
            rs = statement.executeQuery("SELECT * FROM kontak WHERE id_kontak="+idKontak);
            Object [] row = new Object[9];
            while(rs.next()){
                //row[0] = rs.getString("id_kontak");
                fieldNama.setText(rs.getString("nama"));
                fieldTelepon.setText(rs.getString("no_telepon"));
                fieldAlamat.setText(rs.getString("alamat"));
                //row[4] = rs.getString("jenis_kelamin");
                fieldAgama.setText(rs.getString("agama"));
                fieldEmail.setText(rs.getString("email"));
                fieldPekerjaan.setText(rs.getString("pekerjaan"));
                fieldHobi.setText(rs.getString("hobi"));
                fieldTanggalLahir.setText(rs.getString("tanggal_lahir"));
                //model.addRow(row);
            }
            edit=true;
            clicked=true;
        }catch(Exception e){
        
        }
        
        
    }//GEN-LAST:event_tableKontakMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private javax.swing.JButton buttonPencarian;
    private javax.swing.JButton deleteButton;
    private javax.swing.JTextField fieldAgama;
    private javax.swing.JTextField fieldAlamat;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldHobi;
    private javax.swing.JTextField fieldNama;
    private javax.swing.JTextField fieldPekerjaan;
    private javax.swing.JTextField fieldPencarian;
    private javax.swing.JTextField fieldTanggalLahir;
    private javax.swing.JTextField fieldTelepon;
    private javax.swing.JButton imageButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPekerjaan;
    private javax.swing.JLabel profileImage;
    private javax.swing.JButton saveButton;
    private javax.swing.JTable tableKontak;
    // End of variables declaration//GEN-END:variables
}
